"""
StorageAgent — writes inspection records to an Obsidian vault.

Takes a StructuredRecord + CleanedNote and writes them as markdown files
inside the Obsidian vault, organized by hive:

    {vault}/Hives/H{NN}/YYYY-MM-DD.md        — individual inspection
    {vault}/Hives/H{NN}/H{NN}_Index.md       — overview + Dataview queries

Each note uses YAML frontmatter for Dataview compatibility.
"""

from __future__ import annotations

import shutil
from datetime import date, datetime
from pathlib import Path
from typing import Optional

from .base import BuzzAgent
from ..schema import CleanedNote, StructuredRecord, read_artifact


class StorageAgent(BuzzAgent):
    """
    Structured record + cleaned note → Obsidian vault markdown.

    Writes two files per inspection:
      1. Individual note: Hives/H{NN}/YYYY-MM-DD.md
      2. Updated hive index: Hives/H{NN}/H{NN}_Index.md
    """

    # Markdown template for individual inspection notes
    NOTE_TEMPLATE = """---
hive_id: "{hive_id}"
inspection_date: {inspection_date}
queen_seen: {queen_seen}
brood_pattern: {brood_pattern}
brood_health: {brood_health}
mite_count: {mite_count}
honey_frames: {honey_frames}
severity: "{severity}"
issues: {issues}
actions_required: {actions_required}
next_inspection_days: {next_inspection_days}
tags: [beekeeping, inspection, {hive_id}]
created: "{created_at}"
---

# 🐝 Hive {hive_id} — Inspection {inspection_date}

## Summary

{observations}

## Queen Status

{queen_status_display}

## Brood

- **Pattern:** {brood_pattern_display}
- **Health:** {brood_health_display}

## Stores

- **Honey:** {honey_stores}
- **Pollen:** {pollen_stores}
- **Frames of honey:** {honey_frames}

## Issues Found

{issues_display}

## Actions Required

{actions_display}

## Temperament

{temperament}

## Swarm Indicators

{swarm_display}

## Next Steps

- Next inspection recommended in **{next_inspection_days} days**
- Severity: **{severity}**

---

*Generated by BuzzBoard on {generated_at}*
"""

    INDEX_TEMPLATE = """---
hive_id: "{hive_id}"
total_inspections: {total_inspections}
last_inspection: "{last_inspection}"
tags: [beekeeping, hive-index, {hive_id}]
---

# 🐝 Hive {hive_id} — Inspection Log

| Date | Queen | Brood | Mites | Honey | Issues | Severity |
|------|-------|-------|-------|-------|--------|----------|
{rows}

## Dataview

```dataview
TABLE queen_seen, brood_pattern, mite_count, honey_frames, severity
FROM "Hives/{hive_id}"
WHERE inspection_date
SORT inspection_date DESC
```
"""

    def __init__(
        self,
        obsidian_vault: Path,
        pipeline_dir: Optional[Path] = None,
    ):
        super().__init__(name="storage", pipeline_dir=pipeline_dir)
        self.vault = Path(obsidian_vault)
        if not self.vault.exists():
            raise FileNotFoundError(f"Obsidian vault not found: {self.vault}")

    def process(self, input_path: Path) -> Path:
        """
        Read StructuredRecord + CleanedNote → write Obsidian notes.

        Args:
            input_path: Path to a StructuredRecord JSON artifact.
                        The corresponding CleanedNote is found by convention
                        in the same pipeline directory.

        Returns:
            Path to the written Obsidian note.
        """
        # 1. Load structured record
        record = read_artifact(input_path, StructuredRecord)

        # 2. Try to find corresponding CleanedNote for rich text
        cleaned = self._find_cleaned_note(input_path, record)

        print(f"  📁 Storage: {record.hive_id} → Obsidian")

        # 3. Ensure hive directory exists
        hive_dir = self.vault / "Hives" / record.hive_id
        hive_dir.mkdir(parents=True, exist_ok=True)

        # 4. Write individual inspection note
        note_path = hive_dir / f"{record.inspection_date.isoformat()}.md"
        note_content = self._render_note(record, cleaned)
        note_path.write_text(note_content)

        # 5. Update hive index
        index_path = hive_dir / f"{record.hive_id}_Index.md"
        self._update_index(hive_dir, record.hive_id, index_path)

        # 6. Copy artifacts to vault for provenance
        artifact_dir = hive_dir / ".buzzboard"
        artifact_dir.mkdir(exist_ok=True)
        date_str = record.inspection_date.isoformat()
        shutil.copy2(input_path, artifact_dir / f"record_{date_str}.json")
        if cleaned and (cleaned_path := self._find_cleaned_path(input_path)):
            shutil.copy2(cleaned_path, artifact_dir / f"note_{date_str}.json")

        print(f"     Note: {note_path}")
        print(f"     Index: {index_path}")

        return note_path

    # ── Rendering ───────────────────────────────────────────────────────────

    def _render_note(self, record: StructuredRecord, cleaned: Optional[CleanedNote] = None) -> str:
        """Render the full markdown note from structured data."""
        from ..schema import StructuredRecord

        issues_list = "\n".join(f"- {i}" for i in record.issues) if record.issues else "- None"
        actions_list = "\n".join(f"- [ ] {a}" for a in record.actions_required) if record.actions_required else "- None"

        swarm = cleaned.swarm_indicators if cleaned else []
        swarm_display = "\n".join(f"- {s}" for s in swarm) if swarm else "- None reported"

        return self.NOTE_TEMPLATE.format(
            hive_id=record.hive_id,
            inspection_date=record.inspection_date.isoformat(),
            queen_seen=str(record.queen_seen).lower(),
            brood_pattern=cleaned.brood_pattern or "N/A" if cleaned else "N/A",
            brood_health=record.brood_health or "N/A",
            mite_count=record.mite_count if record.mite_count is not None else "N/A",
            honey_frames=record.honey_frames if record.honey_frames is not None else "N/A",
            severity=record.severity or "normal",
            issues=str(record.issues),
            actions_required=str(record.actions_required),
            next_inspection_days=record.next_inspection_days if record.next_inspection_days else "N/A",
            created_at=datetime.now().isoformat(),
            observations=cleaned.observations if cleaned else "See structured data below.",
            queen_status_display=cleaned.queen_status.replace("_", " ").title() if cleaned and cleaned.queen_status else ("Seen" if record.queen_seen else "Not seen"),
            brood_pattern_display=cleaned.brood_pattern.replace("_", " ").title() if cleaned and cleaned.brood_pattern else "N/A",
            brood_health_display=record.brood_health.replace("_", " ").title() if record.brood_health else "N/A",
            honey_stores=cleaned.honey_stores.replace("_", " ").title() if cleaned and cleaned.honey_stores else "N/A",
            pollen_stores=cleaned.pollen_stores.replace("_", " ").title() if cleaned and cleaned.pollen_stores else "N/A",
            temperament=cleaned.temperament.title() if cleaned and cleaned.temperament else "N/A",
            swarm_display=swarm_display,
            issues_display=issues_list,
            actions_display=actions_list,
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        )

    def _update_index(self, hive_dir: Path, hive_id: str, index_path: Path):
        """Regenerate the hive index from all inspection notes."""
        notes = sorted(
            [p for p in hive_dir.glob("*.md") if p.name != f"{hive_id}_Index.md"],
            key=lambda p: p.stem, reverse=True,
        )

        rows = []
        for note_path in notes:
            try:
                # Extract frontmatter fields for the table
                content = note_path.read_text()
                fields = self._parse_frontmatter(content)
                rows.append(
                    f"| {fields.get('inspection_date', note_path.stem)} "
                    f"| {fields.get('queen_seen', 'N/A')} "
                    f"| {fields.get('brood_pattern', 'N/A')} "
                    f"| {fields.get('mite_count', 'N/A')} "
                    f"| {fields.get('honey_frames', 'N/A')} "
                    f"| {', '.join(fields.get('issues', []))[:40] or 'None'} "
                    f"| {fields.get('severity', 'normal')} |"
                )
            except Exception:
                rows.append(f"| {note_path.stem} | - | - | - | - | - | - |")

        last_date = notes[0].stem if notes else "N/A"
        index_content = self.INDEX_TEMPLATE.format(
            hive_id=hive_id,
            total_inspections=len(notes),
            last_inspection=last_date,
            rows="\n".join(rows) if rows else "| — | — | — | — | — | — | — |",
        )
        index_path.write_text(index_content)

    @staticmethod
    def _parse_frontmatter(content: str) -> dict:
        """Quick YAML frontmatter parser (no PyYAML dependency)."""
        if not content.startswith("---"):
            return {}
        parts = content.split("---", 2)
        if len(parts) < 3:
            return {}
        fields = {}
        for line in parts[1].strip().split("\n"):
            if ":" in line:
                key, _, val = line.partition(":")
                val = val.strip().strip('"')
                if val.startswith("[") and val.endswith("]"):
                    val = [v.strip().strip('"') for v in val[1:-1].split(",") if v.strip()]
                elif val.lower() == "true":
                    val = True
                elif val.lower() == "false":
                    val = False
                fields[key.strip()] = val
        return fields

    # ── Helpers ─────────────────────────────────────────────────────────────

    def _find_cleaned_note(self, record_path: Path, record: StructuredRecord) -> Optional[CleanedNote]:
        """Find the corresponding CleanedNote in the pipeline directory."""
        pipeline_dir = record_path.parent
        for f in sorted(pipeline_dir.glob("cleanednote_*.json"), reverse=True):
            try:
                note = read_artifact(f, CleanedNote)
                if note.hive_id == record.hive_id and note.inspection_date == record.inspection_date:
                    return note
            except Exception:
                continue
        return None

    def _find_cleaned_path(self, record_path: Path) -> Optional[Path]:
        """Find the path to the corresponding CleanedNote."""
        pipeline_dir = record_path.parent
        for f in sorted(pipeline_dir.glob("cleanednote_*.json"), reverse=True):
            try:
                note = read_artifact(f, CleanedNote)
                record = read_artifact(record_path, StructuredRecord)
                if note.hive_id == record.hive_id and note.inspection_date == record.inspection_date:
                    return f
            except Exception:
                continue
        return None
